/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Bingo: typeof import('./src/components/Bingo.vue')['default']
    DarkMode: typeof import('./src/components/DarkMode.vue')['default']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Setting: typeof import('./src/components/Setting.vue')['default']
    ThemeSelect: typeof import('./src/components/ThemeSelect.vue')['default']
  }
}
